title: Blog
email: qkboo@thinkbee.kr
description: > # this means to ignore newlines until "baseurl:"
  다양한 프로그래밍 환경을 다루고 Mobile, macOS, Python, Linux Developement 대해서 다루고 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qkboo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gtko
github_username:  qkboo

# deployment
host: 0.0.0.0
port: 4000

# Markdown-kramdown
markdown: kramdown
highlighter:    rouge
kramdown:
  input: GFM
  auto_ids:     true
#  syntax_highlighter: rouge

# Makrdown-redcarpet
# markdown: redcarpet
# highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]



#theme: minima
#gems:
plugins_dir:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
#  - bootstrap
#  - autoprefixer-rails
#  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock

# Disqus
disqus:
  shortname: qkboo-github-io

# Google Analytics
google_analytics: UA-98721340-1


paginate: 6

# Permalink
permalink: /:year/:month/:day/:title

# Collections
collections:
  my_collection:
    output: true


cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
  css_hash:         "sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
  js_hash:          "sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
  jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
  jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  popper_hash:      "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"


toc:
  min_level:        2
  max_level:        4